






name: canshield
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - omegaconf
  - pandas
  - seaborn
  - tqdm
  - yaml
  - hydra-core
  - scikit-learn
  - scipy
  - pip:
      - tensorflow==2.10
      - keras==2.10
      - nvidia-pyindex
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - numpy==1.26.4