







name: canshield
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - omegaconf
  - pandas
  - seaborn
  - tqdm
  - yaml
  - hydra-core
  - scikit-learn
  - scipy
  - pip:
      - tensorflow==2.15
      - keras==2.15
      - nvidia-pyindex
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==8.9.6.50
      - numpy==1.26.4

